### ISSUE TITLE
Error 'OAuth2Strategy requires a clientID option'

### ISSUE THREAD

**Issue by djpbessems** [andrelind/launch-bay-next-web#10]
I threw together a quick dockerimage that builds and runs this (see https://code.spamasaurus.com/djpbessems/Docker.Containers.LaunchBayNext)

But am getting the following error with traceback:
```
/app/launchbaynext # yarn dev
yarn run v1.21.1
$ nodemon
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): server
[nodemon] watching extensions: ts
[nodemon] starting `ts-node --project tsconfig.server.json server.ts`

/app/launchbaynext/node_modules/passport-oauth2/lib/strategy.js:86
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                                 ^
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/app/launchbaynext/node_modules/passport-oauth2/lib/strategy.js:86:34)
    at new Strategy (/app/launchbaynext/node_modules/passport-facebook/lib/strategy.js:56:18)
    at Object.<anonymous> (/app/launchbaynext/passport/providers/facebook.ts:6:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Module.m._compile (/app/launchbaynext/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Object.require.extensions.<computed> [as .ts] (/app/launchbaynext/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/launchbaynext/passport/providers/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Module.m._compile (/app/launchbaynext/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Object.require.extensions.<computed> [as .ts] (/app/launchbaynext/node_modules/ts-node/src/index.ts:817:12)
[nodemon] app crashed - waiting for file changes before starting...
```

Also, what would be the proper way to run the page without using `yarn dev`-mode (I tried the command that is in package.json: `node .next/server -p 80`, but that didn't work either)?

**Comment by djpbessems** [comment]
Disregard my 2nd question: after switching to `npm` instead of `yarn` (see https://iamturns.com/yarn-vs-npm-2018/); it was super easy: `npm run bulid` followed by `npm start`

**Comment by djpbessems** [comment]
Am I right in assuming that I need the following four environment variables?
`FACEBOOK_ID`  
`FACEBOOK_SECRET`  
`GOOGLE_ID`  
`GOOGLE_SECRET`  

Is it possible to avoid using these OAuth providers entirely?

**Comment by djpbessems** [comment]
Ok, adding those 4 environment variables (even with garbage values) gets the website running. Cool!

**Comment by djpbessems** [comment]
I've created my own Google OAuth ID, but apparently I did something wrong:
```
The redirect URI in the request, http://localhost:3000/api/auth/callback/google, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/345379642866-0a43vvh7ra8sv0khs0fs3kt4soedl32o.apps.googleusercontent.com?project=345379642866
```

Does that mean I will have to open up port 3000 as well and change the redirect URI when I create the OAuth Client ID?

**Comment by djpbessems** [comment]
Never mind again; I went into the code and noticed the environment variable `HOSTING_URL`.

Once I set that to the FQDN of my instance of LaunchBayNext and updated the redirect URI in my OAuth Client ID to `https://lbn.example.com/api/auth/callback/google` I was able to log on.

**Comment by Chaiyasuth** [comment]
> Ok, adding those 4 environment variables (even with garbage values) gets the website running. Cool!

Me too, "Even with garbage values" and it have no error anymore. ;D
